### PR TITLE
fix a potential NPE when db executions get exception

### PR DESCRIPTION
**Pull request by raybi-asus**
Sometimes we checked the agent log and found some NullPointerExceptions. 
npe1
I tried to read the log and relevant trace segments, then found it occurred in handleMethodException. 
It means our db execution(insert/update) got some exceptions. 
npe2
Then the enhanced method need to invoke handleMethodException to create a span for errorOccurred. 
`ContextManager.activeSpan().errorOccurred().log(t);`

Now , from the log we can identify the NPE was caused by `cacheObject.getConnectionInfo() != null`. because cacheObject is a null object. I checked the stack trace and found that execute method which was enhanced by agent was invoked several times but different callers. But only one of them is not null and has db connection information .

Hence i'm trying to add a null value judgement for cacheObject to avoid the similar issue. In the meantime it also make the handleMethodException mehod have the same behavior as other methods.
npe3
npe4

Please let me know if you have any concerns.

### CODE REVIEW

**Comment by raybi-asus** [comment]
From CreatePreparedStatementInterceptor of Oracle-plugin , we can see only OraclePreparedStatementWrapper was set SkyWalkingDynamicField. 
np5
It was defined in PhysicalConnection of ojdbc driver.
npe6

But we will intercept all these 3 classes : OraclePreparedStatement , T4CPreparedStatement, OraclePreparedStatementWrapper and all 4 methods as the screenshot
npe7

When the sql exception was occurred , all the execute methods of these 3 classes would be intercepted. But only the other invocation(OraclePreparedStatementWrapper ) has SkyWalkingDynamicField. 

But i think we can not remove other enhanced calsses , because they would still be used in specific case. Such as batchUpdate , executeLargeBatch and so on. 

Therefore i just add a null value judgement for null object to avoid NPE.

Please let me know if you have any concerns.

**Comment by wu-sheng** [comment]
Should we consider separating the intercepting points for different classes? Your explanation makes me feel, we are intercepting unnecessary methods. Am I right?

**Comment by bitray** [comment]
Sorry I left ASUS from last week . Hence I change another account to reply.
Actually I think we don't need to change the existing logic. Because different interceptors are still used for different cases.
As my last reply, batchUpdate , executeLargeBatch methods was implemented in OraclePreparedStatement , T4CPreparedStatement. Maybe someone would use this for some corner cases.

But for current case , we can know that only OraclePreparedStatementWrapper has  SkyWalkingDynamicField , and other inner invocations would get NPE.

In the meantime , this issue is a corner case too. NPE is thrown only when the SQL exception was occurred in ojdbc driver. Other normal cases run well.

**Comment by wu-sheng** [comment]
@bitray Do you want me to merge this or wait for you to open another PR by new ID?

**Comment by bitray** [comment]
@wu-sheng 
Actually I have no idea which is better for management . 
Could you please provide me some suggestions?

**Comment by wu-sheng** [comment]
@bitray If you are still going to work on SkyWalking, I would suggest you open another PR. Because it is easier to find you

**Comment by bitray** [comment]
@wu-sheng OK sure,  thanks for suggestion 

I will create a new PR..

**Comment by JaredTan95** [comment]
new PR https://github.com/SkyAPM/java-plugin-extensions/pull/24

**Pull request closed without merging**
